# SPDX-License-Identifier: GPLv3
name: 'Setup Lix'
author: 'Lunaphied'
description: Use the Lix installer to download a release of Lix and install it.
runs:
  using: 'composite'
  steps:
    - name: Fetch and execute installer and add to path
      shell: bash
      run: |
        if [ ! -f /nix/receipt.json  ]; then
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install linux --no-confirm --init none
        fi
        # Add to the path for the next actions.
        echo "/nix/var/nix/profiles/default/bin" >>"$GITHUB_PATH"
